### PR TITLE
Add bbtools_tadpole, SeqSero2, and RGI

### PR DESCRIPTION
**Pull request by WhoisDonlee**
The RGI wrapper and data manager is provided by card, which is also de developer of RGI. I wasn't sure if this was allowed so let me know if it belongs somewhere else.

I didn't run into any problems running it on our own instance.

https://github.com/arpcard/rgi_wrapper/tree/master

### CODE REVIEW

**Comment by bgruening** [comment]
@WhoisDonlee rgi_database_builder does not seem to be in the TS.

The others are not a problem to install, but the rgi tools need a review or moved to IUC.

**Comment by WhoisDonlee** [comment]
The rgi_database_builder is installed when the rgi_wrapper is installed via the admin panel. I'm not that familiar with data managers, but it looks like it is included in the rgi_wrapper itself and not as a separate tool.

**Comment by bgruening** [comment]
Yes, which is also not good. I think we need to work in the rgi a bit. Do you know the author?

**Comment by WhoisDonlee** [comment]
Ah okay, for now I will remove it and will make it a separate PR once it's in the IUC.
Thanks!

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Supi! This will be installed automatically on Sunday. Let me know if you need it before Xmas :)

**Comment by WhoisDonlee** [comment]
Awesome! Sunday will be fine!

**Pull request merged**
