### PR TITLE
add new category HiCexplorer

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
Will be interesting to see if the automatic system changes this labels in the lock files as well. I haven't changed them manually.

**Comment by erasche** [comment]
It won't :( Will implement that, obvious needed feature.

**Comment by erasche** [comment]
It does now :) and it fixed a bunch of bad ones. https://github.com/usegalaxy-eu/usegalaxy-eu-tools/commit/d884879f127aab155e395dc0ba4c1a3d763dbe25

**Comment by bgruening** [comment]
Danke.

**Pull request merged**
