### PR TITLE
tools_iuc.yaml.lock: add the latest revision for MOABS

### PR DESCRIPTION
**Pull request by lijinbio**

### CODE REVIEW

**Comment by bgruening** [comment]
Merci!

**Comment by lijinbio** [comment]
> Merci!

@bgruening Hi Björn, many thanks for merging the latest revision for MOABS. May I ask when the updated revision will be available at https://usegalaxy.eu/root?tool_id=moabs? We want users to access our updates as soon as possible. Thank you.

**Comment by bgruening** [comment]
@lijinbio I just installed it. Enjoy!

**Comment by bgruening** [comment]
And thanks for your contributions this is awesome!

**Comment by lijinbio** [comment]
> @lijinbio I just installed it. Enjoy!

@bgruening Hi Björn, yes, our interfaces are upgraded now. Many thanks for all your help. Stay safe and have a good weekend.

**Pull request merged**
