### PR TITLE
Add manta

### PR DESCRIPTION
**Pull request by hexylena**
For @scottcain, and, maybe also interesting for @wm75 and my coworkers.

- tool looks ok, artbio is good
- they were careful about quoting https://github.com/ARTbio/tools-artbio/blob/master/tools/manta/manta.xml

should be ok :+1: 
pinging @bgruening (is one of your admin team now handling tool requests, should I ping someone else?)

### CODE REVIEW

**Comment by bgruening** [comment]
I found one script that was unquoted and added a profile version here: https://github.com/ARTbio/tools-artbio/pull/618

**Comment by bgruening** [comment]
@hexylena maybe you can ping the @usegalaxy-eu/admin group?

**Comment by wm75** [comment]
arrgh, https://github.com/galaxyproject/tools-iuc/pull/3140 fell victim to covid, sorry.
I don't remember at all anymore what the status was, nor what I thought of the existing wrapper.

**Comment by hexylena** [comment]
@bgruening yes, can do in the future :) @wm75 ahhh jeez.

**Comment by hexylena** [comment]
> I found one script that was unquoted and added a profile version here: 

looks like just the python file in the tool directory in your PR, so, at least not a security risk, albeit sub-optimal.

**Comment by bgruening** [comment]
I will merge. @wm75 maybe we can migrate this one with this user to IUC if you ever find time to work on it.

**Comment by hexylena** [comment]
Thanks @bgruening , @wm75 !

**Pull request merged**
