### PR TITLE
Update materials tools for MSS 2.2.1 and PMS 0.3.0

### PR DESCRIPTION
**Pull request by patrick-austin**
Adds utility tool for MuSpinSim, and version updates for most `muon-spectroscopy-computational-project` tools.

### CODE REVIEW

**Comment by bgruening** [comment]
@patrick-austin did I simply forget this one? Or was it not ready? Sorry if we just missed it. Please ping us in those cases.

**Comment by patrick-austin** [comment]
There was an issue with `pm-uep-opt` that needing patching with `0.3.0+galaxy1` but now it should be ready to merge. I think I opened this the week after the Australia conference so probably a lot of other things going on at the time.

**Comment by bgruening** [comment]
Do we need to update the loc files? Or is it up to date?

**Comment by patrick-austin** [comment]
`materials.yaml.lock` has all the new revision ids for the tools that have changed and a new entry for `muspinsim_combine` - I think that's everything that needs to change? So it should be up to date as is.

**Review by bgruening — APPROVED** [review]

**Pull request merged**
