### PR TITLE
Update cd-hit which fix a typo for Pavan

### PR DESCRIPTION
**Pull request by bebatut**

### CODE REVIEW

**Comment by bebatut** [comment]
merged by @erasche !!!!!!!

**Comment by bgruening** [comment]
@bebatut can we please get rid of this CD-hit implementation. On IUC are two open PRs with cd-hit migration instructions. On usegalaxy.eu we have now two different cd-hit tools :(

**Comment by erasche** [comment]
@bgruening until the IUC one is merged, we need a functional one to install from the TS. This is it.

**Comment by bgruening** [comment]
> This is it.

What?

The PRs are open since ages. Duplicated tools are a no-go and we should try to avoid it as much as possible. This is it - especially if people are cloning our toolset in the future.

**Comment by bebatut** [comment]
I agree that duplications should be avoided. But cd-hit was already duplicated before (and before the PRs on IUC) and Pavan needed a fix for this tool, so we fixed it and installed the new TS version. 
I will work on the IUC PRs to make sure cd-hit would be there and then we can "deprecate" the other versions

**Comment by bgruening** [comment]
Since when is a duplicated tool an argument for a tripled version of a tool?
We contacted JJ two month ago and he responded immediately, now we have this tool obviously used in workflows and can not get rid of it anymore.

**Pull request merged**
