### PR TITLE
Earlhaminst tools

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
I'm a little bit confused that the test did not fail with the new category.

**Comment by bgruening** [comment]
I guess these needs to be merged before: https://github.com/usegalaxy-eu/galaxy-playbook-temporary/pull/175

**Comment by erasche** [comment]
Tests aren't happening. The build server is still offline. I'm blocked on needing to replace the jenkins worker image.

**Comment by erasche** [comment]
Looks good otherwise, I trust you've written it correctly ;) We'll find out when the build server is back to test the code + run the auto-installation script.

**Pull request merged**
