### PR TITLE
add virhunter tool to IUC.yaml

### PR DESCRIPTION
**Pull request by bdartigues**

### CODE REVIEW

**Comment by bgruening** [comment]
Cool, thanks a lot!

Can you please tell me where and which models I should deploy?

**Comment by bdartigues** [comment]
Dear Bjoern, 
I finally found a way to deal with two or three model sizes depending the content of the models folder. I updated the tool code on tools-iuc repository but i wait for reviewing. 

Do i have to open a new pull request in usegalaxy-eu-tools after that in order to update the tools or is it automatic ?
Many thanks in advance

**Comment by bdartigues** [comment]
Here is the pull request on IUC  => Update Virhunter tool #4957

**Comment by bgruening** [comment]
You do not need to update that on here, this is updated automatically.

**Pull request merged**
