### PR TITLE
remove gmx_npt and gmx_nvt

### PR DESCRIPTION
**Pull request by gmauro**
remove gmx_npt and gmx_nvt as discussed with @simonbray 
These tools run using all cores available in the computing node, making it unusable.

### CODE REVIEW

**Comment by bgruening** [comment]
This will not remove the tools. Removing is not implemented at the moment. Is here a way how we can fix those tools?

Is hiding better?

**Comment by simonbray** [comment]
We could add a set number of cores to the tools here: https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/files/galaxy/dynamic_rules/usegalaxy/tool_destinations.yaml. That would 'fix' the problem.

However, no-one should be using these tools, so it would be better to hide them IMO.

**Comment by gmauro** [comment]
Remove "from the tools' menu"

**Comment by simonbray** [comment]
> Remove "from the tools' menu"

Or block tool execution. I believe someone said this was an option.

**Comment by bgruening** [comment]
Can you see if the tools are.gone?

**Comment by simonbray** [comment]
They are not findable via search, but you can still navigate directly to e.g. https://usegalaxy.eu/?tool_id=gmx_nvt and the tool can also be executed.

**Comment by bgruening** [comment]
Yes they are only hidden. If you really want to remove it we can remove it. I will do this tonoght.

**Comment by simonbray** [comment]
> Yes they are only hidden. If you really want to remove it we can remove it. I will do this tonoght.

I thought this was discouraged in case they are used in workflows?

If it's possible, yes, it would be good if they can be removed - in that case can you also remove `gmx_md` as well please?

**Comment by bgruening** [comment]
Removed from the server. It probably needs to resync.

**Pull request merged**
