### PR TITLE
Add xarray tools to ecology flavour

### PR DESCRIPTION
**Pull request by yvanlebras**

### CODE REVIEW

**Comment by bgruening** [comment]
I know this is confusing, we will use this tool list in the future for the sub-domains, but currently, you need to edit it here: https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/templates/galaxy/config/global_host_filters.py.j2

Which might not be possible, as you need to "show" the climate category :(

**Comment by yvanlebras** [comment]
Thank you Björn, I was researching the link of this file... Thanks !
ITM, it appears that xarray tools are on the usegalaxy.eu "climate_analysis" tool section, I think this can be more appropriate to put these xarray tools on the "GIS data handling" one (or maybe in both ?).

**Comment by bgruening** [comment]
both is at the moment not possible ... @annefou is the GIS section ok for you as well?

**Comment by yvanlebras** [comment]
I can understand that both is not possible for now. 
NetCDF is a data format, so not so easy to classify such related tools on 1 particular tool section. But, this format is used particularly in climate, meteorology, oceanography... in a way that can be IMO summarized as GIS... Waiting for the feedback from Anne.
THANK you again Björn, Thank you Anne !!!

**Comment by annefou** [comment]
GIS section is OK for me.

**Comment by bgruening** [comment]
@yvanlebras can you change the section in the climate yml please as well?

**Comment by yvanlebras** [comment]
Done! Thank you

**Comment by bgruening** [comment]
Ok, tomorrow this should be fixed.

**Pull request merged**
