### PR TITLE
add travis testing

### PR DESCRIPTION
**Pull request by bgruening**
fixes: https://github.com/usegalaxy-eu/usegalaxy-eu-tools/issues/9

### CODE REVIEW

**Comment by bgruening** [comment]
I'm a little bit afraid this breaks @erasche fancy setup, so leaving it to him to merge it.

**Comment by erasche** [comment]
Nope, no effect on jenkins builds whatsoever

**Comment by simonbray** [comment]
This got removed @bgruening?

**Comment by bgruening** [comment]
Yes, Helena has removed is here: https://github.com/usegalaxy-eu/usegalaxy-eu-tools/pull/36/files

I guess we can add it back until we solve the general usegalaxy.* stuff.

**Pull request merged**
