### PR TITLE
Add necat

### PR DESCRIPTION
**Pull request by gallardoalba**

### CODE REVIEW

**Comment by bgruening** [comment]
what was the problem here?

**Comment by gallardoalba** [comment]
> what was the problem here?

I don't understand sorry; I just want to install it, because it is one of the tools recommend in the Genoscope assembly workflow.

**Comment by bgruening** [comment]
Why did you then close the PR ? :)

**Review by bgruening — APPROVED** [review]

**Comment by gallardoalba** [comment]
> Why did you then close the PR ? :)

No idea, I think it was too late XD.

**Pull request merged**
