### PR TITLE
add dewseq + htseq-clip to galaxy

### PR DESCRIPTION
**Pull request by michauhl**
Add DEWSeq + htseq-clip to usegalaxy.eu. It would be great to have a new tool_panel_section_label "CLIP-seq" here, just like there is already one for "ChIP-seq" tools on usegalaxy.eu.

### CODE REVIEW

**Comment by bgruening** [comment]
Is a specific category needed? Can we not fold this into RNA?

**Comment by bgruening** [comment]
Well if you think CLIP deserves its own category than ChIP ;) Then please add the new category to the schema file in this repo, so that the test does pass. Thanks.

**Comment by michauhl** [comment]
I see, it's probably too much work (weird I thought there is a ChIP-seq category, but there is none). So let's just put them under "Peak Calling"

**Comment by bgruening** [comment]
@michauhl ping

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks.

**Comment by michauhl** [comment]
Thank you Björn :) How about memory requirements of tools? Do you specify this in another file on here ?

**Comment by bgruening** [comment]
We are currently migrating this, lets take the new one here: https://github.com/galaxyproject/tpv-shared-database/blob/main/tools.yml

@mira-miracoli can help you if needed I think.

**Comment by michauhl** [comment]
I gathered the following requirements:
dewseq: 40GB RAM, 2 cores
htseq_clip: 16GB RAM, 4 cores
@mira-miracoli can you add these stats? I'm not sure how to specify these in https://github.com/galaxyproject/tpv-shared-database/blob/main/tools.yml

**Pull request merged**
