### PR TITLE
multiqc is now in IUC

### PR DESCRIPTION
**Pull request by bgruening**
remove QC from the lable

### CODE REVIEW

**Comment by erasche** [comment]
- [ ] fix label in https://github.com/usegalaxy-eu/galaxy-playbook-temporary/blob/master/roles/galaxy_config/templates/tool_conf.xml#L665
- [ ] fix label in .schema.yml

**Comment by bgruening** [comment]
Mh, this label should really go away, it is now: https://github.com/usegalaxy-eu/galaxy-playbook-temporary/blob/master/roles/galaxy_config/templates/tool_conf.xml#L170

**Comment by erasche** [comment]
great, then please remove the other one. I'll:

- [ ] update shed_tool_conf.xml

**Comment by bgruening** [comment]
xref: https://github.com/usegalaxy-eu/galaxy-playbook-temporary/pull/50

**Comment by bgruening** [comment]
Please note that I removed a few more categories, as the NGS prefix should be gone.

**Comment by erasche** [comment]
Can you remove from here as well? https://github.com/usegalaxy-eu/usegalaxy-eu-tools/blob/40eb816f899ad067cec2c00a46a19e3ab91256ab/.schema.yaml#L33

**Comment by erasche** [comment]
Ok, looks good!

**Pull request merged**
