### PR TITLE
Astronomical Archives (IVOA) Data Source tools

### PR DESCRIPTION
**Pull request by volodymyrss**
Astronomical Archives (IVOA) Data Source tools

https://toolshed.g2.bx.psu.edu/view/astroteam/astronomical_archives/0ddfc343f9f9

developed by @francoismg

### CODE REVIEW

**Comment by francoismg** [comment]
I can find the tool when searching the toolshed from my galaxy instance, but some things seems weird, will upload a screenshot

**Comment by volodymyrss** [comment]
> I can find the tool when searching the toolshed from my galaxy instance, but some things seems weird, will upload a screenshot

I imagine toolshed instability might be the cause. But then this PR here managed to find and test the tool, right?

**Comment by francoismg** [comment]
Screenshot 2023-09-04 at 16 45 40
Screenshot 2023-09-04 at 16 46 52


> > I can find the tool when searching the toolshed from my galaxy instance, but some things seems weird, will upload a screenshot
> 
> I imagine toolshed instability might be the cause. But then this PR here managed to find and test the tool, right?

yes it seems like it was able to do so since it uploaded it to the tool shed and maybe the remaining problem are just caused by some instability like you said

**Comment by volodymyrss** [comment]
> But I'm not sure about the fact that there's an "astroteam" version and a "volodymyr.savchenko" version, do you have that too?

Yes, I changed it in the .shed.yml, it should be astroteam, but first version went with my account which is not right.

Does it work to download the astroteam one?

**Comment by francoismg** [comment]
> > But I'm not sure about the fact that there's an "astroteam" version and a "volodymyr.savchenko" version, do you have that too?
> 
> Yes, I changed it in the .shed.yml, it should be astroteam, but first version went with my account which is not right.
> 
> Does it work to download the astroteam one?

yes the astroteam one seems to work

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Its installed now.

**Pull request merged**
