### PR TITLE
add mcl tool

### PR DESCRIPTION
**Pull request by coeit**
## Add mcl markov clustering tool

Request to add [mcl](https://micans.org/mcl/) - [galaxy-wrapper](https://toolshed.g2.bx.psu.edu/repository?repository_id=d55826498c75f75f&changeset_revision=60609b076830) as a tool. It is maintained by "brinkmanlab" here: https://github.com/brinkmanlab/galaxy-tools/tree/master/mcl.

Since no other tool from this maintainer is available i created a new yaml file. Feel free to change that if there is a more appropriate place for it.

### CODE REVIEW

**Comment by bgruening** [comment]
We need to fix this tool first, or enhance it. Do you have time to work on this one and push it over the line? https://github.com/galaxyproject/tools-iuc/pull/4558

I'm traveling next week and probably have no time :(

**Comment by coeit** [comment]
I can try to make some advances. Not sure what it needs though to be "over the line". I'm guessing adding some missing input parameters +  adding some tests?

**Comment by bgruening** [comment]
More or less addressing the review comments. If you need some additional parameters please add them, but the other comments are more important I think.

**Comment by coeit** [comment]
@bgruening, sorry but i didn't really had time this week to advance on that issue, lots of other things going on... I hope I can find some time next week. Anyway i'll keep an eye on the issue in case you find some time to address some of the points. I'd still like to contribute either way!

**Comment by bgruening** [comment]
Oh sorry, was just one minute faster :)

**Comment by bgruening** [comment]
I will also trigger a manual installation now of MCL

**Comment by coeit** [comment]
> Oh sorry, was just one minute faster :)

Ups, I see. I merged upstream now as well.

**Comment by bgruening** [comment]
I added it in https://github.com/usegalaxy-eu/usegalaxy-eu-tools/commit/d6243ce14f49d9d3cb6c88fb255fff6baa87724d to Multiple Alignment

Do you think this is ok?

**Comment by bgruening** [comment]
ok! I'm buying that :)

**Comment by coeit** [comment]
> ok! I'm buying that :)

In theory it is unsupervised learning.

**Pull request merged**
