### PR TITLE
fix yaml to get only one section_label per tool

### PR DESCRIPTION
**Pull request by lldelisle**
I used:
```python
#!/usr/bin/env python
import glob
import json
import os
import sys
import ruamel.yaml

disambig = {}
if len(sys.argv) > 1:
    pref_json_fn = sys.argv[1]
    with open(pref_json_fn, 'r') as f:
        disambig = json.load(f)


yaml = ruamel.yaml.YAML()
yaml.preserve_quotes = True

for fn in sorted(glob.glob("*.yaml")):
    with open(fn, 'r') as handle:
        tools = yaml.load(handle)
        for x in tools['tools']:
            name=f"{x['owner']}/{x['name']}"
            if 'tool_panel_section_label' in x:
                if name in disambig:
                    x['tool_panel_section_label'] = disambig[name]
    
    with open(fn, 'w') as fo:
        yaml.dump(tools, fo)
```
and:
```json
{
    "bebatut/format_cd_hit_output": "Multiple Alignments",
    "bgruening/interproscan5": "Annotation",
    "bgruening/pileometh": "Peak Calling",
    "crs4/taxonomy_krona_chart": "Metagenomic Analysis",
    "devteam/basecoverage": "Operate on Genomic Intervals",
    "devteam/cluster": "Operate on Genomic Intervals",
    "devteam/complement": "Operate on Genomic Intervals",
    "devteam/draw_stacked_barplots": "Graph/Display Data",
    "devteam/kraken": "Metagenomic Analysis",
    "devteam/kraken_filter": "Metagenomic Analysis",
    "devteam/kraken_report": "Metagenomic Analysis",
    "devteam/kraken_translate": "Metagenomic Analysis",
    "devteam/kraken2tax": "Metagenomic Analysis",
    "devteam/subtract": "Operate on Genomic Intervals",
    "ecology/cb_dissim": "Compute indicators for turnover boulders fields",
    "ecology/cb_ivr": "Compute indicators for turnover boulders fields",
    "ethevenot/biosigner": "Statistics",
    "ethevenot/heatmap": "Statistics",
    "ethevenot/multivariate": "Statistics",
    "ethevenot/transformation": "Statistics",
    "ethevenot/univariate": "Statistics",
    "galaxyp/idpquery": "Convert Formats",
    "galaxyp/msconvert": "Convert Formats",
    "galaxyp/msms_extractor": "Convert Formats",
    "galaxyp/thermo_raw_file_converter": "Convert Formats",
    "goeckslab/mesmer": "Spatial Omics",
    "hammock/hammock": "Multiple Alignments",
    "iuc/bbtools_bbduk": "FASTA/FASTQ",
    "iuc/bwameth": "Mapping",
    "iuc/kraken_taxonomy_report": "Metagenomic Analysis",
    "iuc/prinseq": "FASTA/FASTQ",
    "iuc/rnaquast": "Assembly",
    "lecorguille/anova": "Statistics",
    "peterjc/sample_seqs": "NCBI Blast",
    "prog/lcmsmatching": "Annotation",
    "sauria/hifive": "Epigenetics"
}
```

So in addition to the section_label changes there are a lot of 'linting'.
(However, I manually put back the indentation of tools)

### CODE REVIEW

**Review by hexylena — COMMENTED** [review]
thanks so much for fixing all of these up :) do the lock files also need to be fixed then?

**Comment by lldelisle** [comment]
Oops... You are right. I forgot to change the lock files... I will do it...

**Comment by lldelisle** [comment]
I would like people to approve some changes:
Proteomics:
```
    "galaxyp/idpquery": "Convert Formats",
    "galaxyp/msconvert": "Convert Formats",
    "galaxyp/msms_extractor": "Convert Formats",
    "galaxyp/thermo_raw_file_converter": "Convert Formats",
```
For me:
```
    "peterjc/sample_seqs": "NCBI Blast",
```
Is strange I would put FASTA/FASTQ (or Filter and Sort)... because description is: 
```
Takes an input file of sequences (typically FASTA or FASTQ, but also
Standard Flowgram Format (SFF) is supported), and returns a new sequence
file sub-sampling from this (in the same format).
```

**Comment by lldelisle** [comment]
Please @peterjc and @foellmelanie, would you mind to check that the category changes for the tools above seems good or if you prefer another 'panel_label'?
Thanks

**Comment by peterjc** [comment]
I don't understand why my https://github.com/peterjc/pico_galaxy/tree/master/tools/sample_seqs would have been put under "NCBI BLAST", perhaps and error as some of my other tools do fit there. The existing "Filter and Sort" makes more sense.

**Comment by lldelisle** [comment]
It seems that it was both in 'Filter and Sort' and in 'NCBI BLAST'. It is fixed. Thanks for you reply.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @lldelisle

**Comment by lldelisle** [comment]
What about the convert format?
Could someone from proteomic or metabolomic could check this before I update the tool_panel_label?
```json
{
    "ethevenot/transformation": "Metabolomics",
    "ethevenot/univariate": "Metabolomics",
    "ethevenot/multivariate": "Metabolomics",
    "ethevenot/biosigner": "Metabolomics",
    "ethevenot/heatmap": "Metabolomics",
    "prog/lcmsmatching": "Metabolomics",
    "galaxyp/idpquery": "Convert Formats",
    "galaxyp/msconvert": "Convert Formats",
    "galaxyp/msms_extractor": "Convert Formats",
    "galaxyp/thermo_raw_file_converter": "Convert Formats",
    "lecorguille/anova": "Statistics"
}
```
Thanks.
@foellmelanie @lecorguille

**Comment by lldelisle** [comment]
Please put your approval to #655. Thanks

**Pull request merged**
