### PR TITLE
Add new tools pathifier and gsc_scran_normalize from artbio based on …

### PR DESCRIPTION
**Pull request by pavanvidem**
…a user request

### CODE REVIEW

**Comment by bgruening** [comment]
@pavanvidem have you checked briefly if those tools are "safe"?

**Comment by pavanvidem** [comment]
They're from [artbio](https://github.com/ARTbio/tools-artbio). We already have some of their tools on EU server. Anyways, I checked them and they look good.

**Comment by bgruening** [comment]
They will be installed at the weekend, is that enough?

**Comment by pavanvidem** [comment]
Thanks!

**Pull request merged**
