### PR TITLE
Move peterjc tools to its own YAML file

### PR DESCRIPTION
**Pull request by gallardoalba**

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Alternatively we could create a peterjc yaml file.

**Comment by gallardoalba** [comment]
> Please do not remove tools form yamls, replications are ok. Just create a new file. Thanks

Now it is fine I think.

**Comment by gmauro** [comment]
@gallardoalba yaml.lock files are automatically generated. Add your new yaml file in the makefile in the [update_trusted](https://github.com/usegalaxy-eu/usegalaxy-eu-tools/blob/54b86ee9faeba591e7124f1fbd41ba5eb02e5448/Makefile#L37) section

**Comment by gallardoalba** [comment]
> @gallardoalba yaml.lock files are automatically generated. Add your new yaml file in the makefile in the [update_trusted](https://github.com/usegalaxy-eu/usegalaxy-eu-tools/blob/54b86ee9faeba591e7124f1fbd41ba5eb02e5448/Makefile#L37) section

Done, but it shows this error: `FileNotFoundError: [Errno 2] No such file or directory: 'peterjc.yaml.lock'` should I run the makefile?

**Comment by gmauro** [comment]
uhmm, the script assumes that the lock file exists before the first execution. If you run `make fix`, it will create the lock.

**Review by gmauro — APPROVED** [review]

**Comment by gmauro** [comment]
and now let's see from where the smoke comes... xD
Thanks @gallardoalba

**Pull request merged**
