### PR TITLE
add mudirac, remove deprecated tools

### PR DESCRIPTION
**Pull request by subindev-d**
removed the deprecated tool
added new tool - mudirac

### CODE REVIEW

**Comment by bgruening** [comment]
@subindev-d we normally don't remove tools for reproducibility reasons. We can hide them or add a deprecation badge to it if you like.

On the other hand its your community and you decide if reproducibility is important and if old workflows should still be able to run.

What do you think?

**Comment by bgruening** [comment]
Ok, please don't remove them from the list and provide me a list with tool IDs that I need to hide.

**Comment by subindev-d** [comment]
> Ok, please don't remove them from the list and provide me a list with tool IDs that I need to hide.
@bgruening , these three are the tool to be hided
- pm_dftb_opt
- pm_muairss_write
- pm_yaml_config

**Comment by bgruening** [comment]
Ok, should be hidden tomorrow.

**Pull request closed without merging**
