### PR TITLE
API label curation

### PR DESCRIPTION
**Pull request by lldelisle**
Using https://github.com/usegalaxy-eu/usegalaxy-eu-tools/pull/648#issuecomment-1810296957 and Yvan's answer.

### CODE REVIEW

**Comment by lldelisle** [comment]
ping @bgruening @hexylena

**Comment by bgruening** [comment]
If you have time, please change the tool category in the repo. I will merge and for it locally.
If not I try to do that over the weekend.

**Comment by hexylena** [comment]
yeah, agreed, we can just correct them, then we wouldn't need extra infrastructure around maintaining disambiguations.

**Comment by lldelisle** [comment]
Then I misunderstood your comment @bgruening : https://github.com/usegalaxy-eu/usegalaxy-eu-tools/issues/649#issuecomment-1810489851
You want tools to be in multiple files but not multiple 'tool_panel_section_label', right?

**Comment by lldelisle** [comment]
See #652

**Comment by bgruening** [comment]
Correct yes, sorry if I was not clear.

**Pull request closed without merging**
