### PR TITLE
first Astronomy tools

### PR DESCRIPTION
**Pull request by volodymyrss**
Following https://github.com/esg-epfl-apc/tools-astro/pull/7#issuecomment-1599499739 .
Not sure if all is right, e.g. how to identify the owner, galaxy account public name?

Thanks!

### CODE REVIEW

**Comment by bgruening** [comment]
The owner is the TS owner. The account that you used to push to the TS.

**Comment by volodymyrss** [comment]
> The owner is the TS owner. The account that you used to push to the TS.

Ok, done. Anything else? Do we wait Saturday?

**Comment by bgruening** [comment]
No thats it. If you want it earlier I can trigger an install, otherwise, we wait until Saturday.

**Review by bgruening — APPROVED** [review]

**Comment by volodymyrss** [comment]
> No thats it. If you want it earlier I can trigger an install, otherwise, we wait until Saturday.

Ok! It could be interesting if it's not too much trouble to have them earlier, to help prepare for PASC, but it's not critical.

**Comment by bgruening** [comment]
Mh, something is wrong. The repos are not filled in the TS.

**Comment by bgruening** [comment]
https://github.com/esg-epfl-apc/tools-astro/actions/runs/5326990129

**Comment by volodymyrss** [comment]
It uses the original git repository?

**Comment by bgruening** [comment]
ping me on matrix if you can ...

**Comment by bgruening** [comment]
did you create your own CI testing? :)

You can take it from here: https://github.com/galaxyproject/tools-iuc/tree/main/.github/workflows
Then on merge-to-master everything is pushed on your behalf.

**Comment by bgruening** [comment]
But since you are not using CI to push ... how have you pushed? Manually with planemo?

**Comment by volodymyrss** [comment]
> But since you are not using CI to push ... how have you pushed? Manually with planemo?

We continue in matrix, but for the reference, [yes](https://planemo.readthedocs.io/en/latest/publishing.html)

**Pull request merged**
