### PR TITLE
Fix categories

### PR DESCRIPTION
**Pull request by bgruening**
Just a start ...

### CODE REVIEW

**Comment by erasche** [comment]
rebased for new linting.

**Comment by erasche** [comment]
Some new things to fix I'm afraid.

**Comment by bgruening** [comment]
I rather think your linter is not correct ;)
There is also `tool_panel_section_id` which is used a lot. `tool_panel_section_id` is very specific and what Galaxy is using the `tool_panel_section_label` is converted with a strange, but deterministic algorithm to an ID.

**Comment by erasche** [comment]
Ah, I missed that one. Will correct the testing. :)

**Pull request merged**
