### PR TITLE
new ecology tools

### PR DESCRIPTION
**Pull request by bgruening**
ping @yvanlebras 

We need a category for it ... `Ecology`?

### CODE REVIEW

**Comment by yvanlebras** [comment]
hmmmm...
Ecology can be ok as this is really dedicated to the ecology field.. Here it's abundance index calculation... 
Maybe `Species abundance` ?

**Comment by yvanlebras** [comment]
if we want to give some precisions....

**Comment by bgruening** [comment]
Your call ... keep in mind to not create too many sections.

Let me know and I will adopt it.

**Comment by yvanlebras** [comment]
I think `Species abundance` is a good section name where we will put a lot of tools.
Thank you

**Pull request merged**
