### PR TITLE
Add Stacks2 tool suite

### PR DESCRIPTION
**Pull request by yvanlebras**

### CODE REVIEW

**Comment by bgruening** [comment]
Muha, this is now working right? @yvanlebras @bernt-matthias do you want to write a small paragraph about those tools at https://github.com/usegalaxy-eu/website/tree/master/_posts it will be linked to the Galaxy Hub as well.

**Comment by yvanlebras** [comment]
True, it works wonderfully! Thank you so much Matthias! I think this is a very good idea Björn. You can start something Matthias ?

**Comment by bernt-matthias** [comment]
Will think about it. Are there any changes needed in the gtn tutorial or the work flow shipped with the tutorial? Then we would have the complete package..

**Comment by bgruening** [comment]
That is a question for @yvanlebras. Imho he tried the tutorial and it worked fine for him.

**Comment by yvanlebras** [comment]
with stacks2 the training was ok. I have to update the material with this new version

**Comment by bernt-matthias** [comment]
I think training update should be done first.

**Pull request merged**
