### PR TITLE
change name

### PR DESCRIPTION
**Pull request by bgruening**
ping @simonbray 

Since this is not a suite the name was taken directly from the shed.yml file.

### CODE REVIEW

**Comment by simonbray** [comment]
@bgruening are you sure this was correct? the tool hasn't been added to usegalaxy.eu

**Comment by bgruening** [comment]
It's called mordred: https://toolshed.g2.bx.psu.edu/view/bgruening/mordred

**Comment by bgruening** [comment]
But interestingly it was not added to the lock file :(

https://github.com/usegalaxy-eu/usegalaxy-eu-tools/commit/a41e0a6475a9283bc1af91447f4d294d6762795f

**Comment by erasche** [comment]
It was, just in the commit directly previous to the one you linked. https://github.com/usegalaxy-eu/usegalaxy-eu-tools/commit/449ab7600385bbe4f6813b9ed1e6d9ad1044a476

**Comment by bgruening** [comment]
@simonbray it's here: https://github.com/usegalaxy-eu/usegalaxy-eu-tools/blob/master/cheminformatics.yaml.lock#L251

But not installed, not sure why. Do you need it now?

**Comment by erasche** [comment]
@bgruening it's not installed because installation failed at a previous tool:

```
bioblend.ConnectionError: GET: error 404: '{"status": "error", "message": "No repository named get_pdb found with owner bgruening"}', 0 attempts left: {"status": "error", "message": "No repository named get_pdb found with owner bgruening"}
```

**Comment by erasche** [comment]
I think this will apply to several tools:

- bgruening / get_pdb
- bgruening / get_pubchem_as_smiles
-

**Comment by simonbray** [comment]
Fixed the tool names here: https://github.com/usegalaxy-eu/usegalaxy-eu-tools/pull/187

**Pull request merged**
