### PR TITLE
added new tool: imaging > spot_detection_2d

### PR DESCRIPTION
**Pull request by qgao-hd**
imaging.yaml has been edited.

### CODE REVIEW

**Comment by bgruening** [comment]
And now its passed :) 

Thanks!

**Comment by bgruening** [comment]
It will be installed on Saturday if you don't need it earlier.

**Comment by qgao-hd** [comment]
> It will be installed on Saturday if you don't need it earlier.

Thanks. It will be great if this and the following two tools could all be installed on Saturday. Then I can start making the new workflows for our partners.

**Comment by bgruening** [comment]
They should be installed.

**Pull request merged**
