### PR TITLE
Add cpat and pfam scan

### PR DESCRIPTION
**Pull request by gallardoalba**

### CODE REVIEW

**Comment by bgruening** [comment]
deployment of one tool failed, I will try to fix that and rerun the tests here

**Comment by gallardoalba** [comment]
> deployment of one tool failed, I will try to fix that and rerun the tests here

Did you find what was the problem with PfamScan?

**Comment by bgruening** [comment]
yes, I fixed that ...

**Comment by gallardoalba** [comment]
> yes, I fixed that ...

Thanks!

**Pull request merged**
