### PR TITLE
Remove humann with old versioning (Humann2)

### PR DESCRIPTION
**Pull request by tuncK**
Else, it pops up in the search box as if it is a separate tool.

### CODE REVIEW

**Comment by bgruening** [comment]
This will not uninstall tools, we do not uninstall tools at all and don't have a procedure for it.

I can hide tools if you like.

**Comment by tuncK** [comment]
Hmmm, OK. Then yes, can you please hide humann2*?

**Comment by bgruening** [comment]
Can you see if I have hidden all in 10min?

**Comment by tuncK** [comment]
Yes, hiding worked as of today 12:27. Thanks

**Comment by bgruening** [comment]
Can we close this?

**Pull request closed without merging**
