### PR TITLE
Update ecology.yaml add dead wood indicator from geometric mean

### PR DESCRIPTION
**Pull request by yvanlebras**

### CODE REVIEW

**Comment by bgruening** [comment]
Is failing...

**Comment by yvanlebras** [comment]
"Indicators from geometric mean" tool section doesn't exist. I need to create it

**Comment by yvanlebras** [comment]
This https://github.com/usegalaxy-eu/infrastructure-playbook/pull/1069 is not sufficient to do so?

**Comment by yvanlebras** [comment]
THANK YOU wonder Björn ! HAve a nice week end !!

**Pull request merged**
