### PR TITLE
Added toolshed tools for spatialOMICS.

### PR DESCRIPTION
**Pull request by FloWuenne**
Added a spatialomics.yaml file with core MCMICRO tools available from toolshed.

### CODE REVIEW

**Comment by bgruening** [comment]
I can unfortunately not change the files in your PR. Can you change the label to "Spatial Omics" please.

**Comment by FloWuenne** [comment]
I changed the label as you asked @bgruening . Was this the reason the workflow failed though?

**Comment by bgruening** [comment]
Yes this was the reason. I added a new catagory to our linter. This looks now very good. I'm working with the US people to update the tools and add tests. Not sure how long this will take.
Can we wait with merging here until the tools are in a better shape?

**Comment by bgruening** [comment]
Thanks @FloWuenne for all your PRs. This is all what was needed to setup an own subdomain.

**Comment by FloWuenne** [comment]
Of course we can wait. It would be nice to have them to test them early to make sure everything works, but if it's better to tune tests etc then we can also just wait.

**Comment by FloWuenne** [comment]
@bgruening According to Allison the tests and lintings for the tools should be working now? 

Can we merge this and are we missing any tools that have recently been added to the MCMICRO Galaxy workflow?

**Comment by bgruening** [comment]
https://github.com/usegalaxy-eu/usegalaxy-eu-tools/pull/524 is a replacement. I could not push to your branch.

**Pull request closed without merging**
