### PR TITLE
Add missing tools from samtools suite

### PR DESCRIPTION
**Pull request by mvdbeek**
Many of these are tools added by @bernt-matthias and are very useful.

### CODE REVIEW

**Comment by bgruening** [comment]
Gracias!

**Comment by bernt-matthias** [comment]
@pvanheus was missing `samtools view` on usegalaxy.eu (https://github.com/galaxyproject/tools-iuc/pull/2649)

I also would suggest to deprecate `Filter SAM or BAM, output SAM or BAM files on FLAG MAPQ RG LN or by region` here and at IUC in favor of samtools view.

**Comment by bgruening** [comment]
We still have some problems with installing tools in 19.09, sorry, this will deployed sometime soon. Or I just do it manually for now.

**Comment by bgruening** [comment]
Should be online now ...

**Pull request merged**
