### PR TITLE
[Astro] Update IVOA. Add HESS, SGWB

### PR DESCRIPTION
**Pull request by dsavchenko**

### CODE REVIEW

**Comment by bgruening** [comment]
Do you need this today, or can we wait until the weekend when it's installed automatically?

**Comment by dsavchenko** [comment]
I think it's ok to wait. I will add few more tools meanwhile with separate PR

**Comment by bgruening** [comment]
Cool, thanks!

**Comment by dsavchenko** [comment]
Apparently, the tools were not updated during weekend. Is there some problem in CI/CD?

**Comment by bgruening** [comment]
Can you please check again?

**Comment by dsavchenko** [comment]
> Can you please check again?

Deployed now, thanks

**Pull request merged**
